name: SPFx CI CD

on:
  push:
    branches: [ demo ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 10.x
      
      - name: Install dependencies
        run: npm install

      - name: Build solution
        run: gulp build
        
      - name: Execute Tests
        run: npm test
        
      - name: Bundle and package solution
        run: |
          gulp bundle --ship
          gulp package-solution --ship

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: packageFile
          path: sharepoint/solution/test-list-items.sppkg
    
  deploy:
    
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: packageFile
    
      - name: CLI for Microsoft 365 Login
        uses: pnp/action-cli-login@v2.0.0
        with:
          ADMIN_USERNAME: ${{ secrets.ADMINUSERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMINPASSWORD }}
          
      - name: CLI for Microsoft 365 Deploy App
        uses: pnp/action-cli-deploy@v2.0.0
        with:
          APP_FILE_PATH: test-list-items.sppkg
          SCOPE: sitecollection
          SITE_COLLECTION_URL: https://aakashbhcl.sharepoint.com/sites/AOSDemo
          OVERWRITE: true
